name: biblio_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.3.0
  - requests>=2.25.0
  - jupyter>=1.0.0
  - matplotlib>=3.3.0
  - seaborn>=0.11.0
  - openpyxl>=3.0.0
  - pip
  - pip:
    - jrc_common